"""
Export extracted SeisComP data to CSV, GeoJSON and ZIP formats.
"""
from __future__ import annotations

import csv
import io
import json
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional


# ──────────────────────────────────────────────────────────────────────────────
# Filename sanitiser
# ──────────────────────────────────────────────────────────────────────────────

_RESERVED = re.compile(r"^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$", re.IGNORECASE)
_UNSAFE = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def sanitize_filename(name: str, max_length: int = 180) -> str:
    s = _UNSAFE.sub("_", str(name))
    s = re.sub(r"^\.+", "", s)
    s = re.sub(r"\.+$", "", s)
    s = re.sub(r"\s+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    if _RESERVED.match(s):
        s = f"file_{s}"
    if len(s) > max_length:
        s = s[:max_length - 3] + "..."
    return s or "unnamed_file"


# ──────────────────────────────────────────────────────────────────────────────
# CSV
# ──────────────────────────────────────────────────────────────────────────────

def generate_csv(records: List[Dict[str, Any]], selected_fields: List[str]) -> str:
    """Return CSV string (header + rows) for the given records."""
    if not records:
        return ""
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(selected_fields)
    for rec in records:
        row = []
        for f in selected_fields:
            v = rec.get(f)
            row.append("" if v is None else str(v))
        writer.writerow(row)
    return buf.getvalue()


# ──────────────────────────────────────────────────────────────────────────────
# GeoJSON
# ──────────────────────────────────────────────────────────────────────────────

def generate_geojson(records: List[Dict[str, Any]], selected_fields: List[str]) -> Dict:
    """Return a GeoJSON FeatureCollection dict."""
    features = []
    for rec in records:
        lat = rec.get("station_latitude") or rec.get("event_latitude")
        lon = rec.get("station_longitude") or rec.get("event_longitude")
        if lat is None or lon is None:
            continue
        props = {
            f: rec.get(f)
            for f in selected_fields
            if f not in ("station_latitude", "station_longitude")
        }
        features.append({
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [lon, lat]},
            "properties": props,
        })

    return {
        "type": "FeatureCollection",
        "features": features,
        "metadata": {
            "generated":        datetime.now(tz=timezone.utc).isoformat(),
            "total_stations":   len(records),
            "valid_coordinates": len(features),
            "selected_fields":  selected_fields,
        },
    }


# ──────────────────────────────────────────────────────────────────────────────
# Summary report
# ──────────────────────────────────────────────────────────────────────────────

def create_summary(results: List[Dict], fmt: str) -> str:
    now = datetime.now(tz=timezone.utc).isoformat()
    total_stations = sum(r.get("stationCount", 0) for r in results)
    files_with_data = sum(1 for r in results if r.get("stationCount", 0) > 0)
    lines = [
        "SeisComP Station Data Extraction Summary",
        f"Generated: {now}",
        "=" * 42,
        "",
        "PROCESSING REPORT:",
        f"  Events Processed : {len(results)}",
        f"  Total Records    : {total_stations}",
        f"  Files with Data  : {files_with_data}",
        f"  Output Format    : {fmt}",
        "",
        "EVENT DETAILS:",
    ]
    for i, r in enumerate(results, 1):
        ver = r.get("schemaVersion", "?")
        lines.append(
            f"  {i:>4}. {r.get('eventId', '?')}  "
            f"({r.get('stationCount', 0)} records, schema {ver})"
        )
    lines += ["", "Generated by SeisComP Extractor (Python CLI/GUI)"]
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# ZIP export
# ──────────────────────────────────────────────────────────────────────────────

def export_to_zip(
    results: List[Dict],
    output_path: str | Path,
    fmt: str,
    selected_fields: List[str],
    progress_callback: Optional[Callable[[int, int, str], None]] = None,
) -> Path:
    """
    Write a ZIP archive to *output_path*.

    fmt: 'csv' | 'geojson' | 'both'
    Returns the resolved output path.
    """
    output_path = Path(output_path)
    total_files = len(results) * (2 if fmt == "both" else 1)
    done = 0

    seen_names: set[str] = set()

    def _unique(base: str, ext: str) -> str:
        name = f"{base}.{ext}"
        if name not in seen_names:
            seen_names.add(name)
            return name
        i = 2
        while True:
            name = f"{base}_{i}.{ext}"
            if name not in seen_names:
                seen_names.add(name)
                return name
            i += 1

    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED,
                         compresslevel=6) as zf:
        for result in results:
            eid = result.get("eventId", "unknown")
            clean = sanitize_filename(eid)
            recs = result.get("records", [])

            if fmt in ("csv", "both"):
                csv_data = generate_csv(recs, selected_fields)
                content = csv_data if csv_data.strip() else f"# No data for event {eid}\n"
                fname = _unique(f"csv/{clean}_stations", "csv")
                zf.writestr(fname, content)
                done += 1
                if progress_callback:
                    progress_callback(done, total_files, f"CSV: {eid}")

            if fmt in ("geojson", "both"):
                gj = generate_geojson(recs, selected_fields)
                fname = _unique(f"geojson/{clean}_stations", "geojson")
                zf.writestr(fname, json.dumps(gj, indent=2))
                done += 1
                if progress_callback:
                    progress_callback(done, total_files, f"GeoJSON: {eid}")

        zf.writestr("README_processing_summary.txt", create_summary(results, fmt))

    return output_path


# ──────────────────────────────────────────────────────────────────────────────
# Per-event file export
# ──────────────────────────────────────────────────────────────────────────────

def export_single_event(
    result: Dict,
    output_dir: str | Path,
    fmt: str,
    selected_fields: List[str],
) -> List[Path]:
    """Write one event's data to flat files. Returns list of created paths."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    eid = result.get("eventId", "unknown")
    clean = sanitize_filename(eid)
    recs = result.get("records", [])
    created: List[Path] = []

    if fmt in ("csv", "both"):
        p = output_dir / f"{clean}_stations.csv"
        p.write_text(generate_csv(recs, selected_fields), encoding="utf-8")
        created.append(p)

    if fmt in ("geojson", "both"):
        p = output_dir / f"{clean}_stations.geojson"
        p.write_text(
            json.dumps(generate_geojson(recs, selected_fields), indent=2),
            encoding="utf-8",
        )
        created.append(p)

    return created
