"""
Field definitions — all extractable + calculated output fields.
"""
from __future__ import annotations

FIELD_CATEGORIES: dict[str, dict] = {
    "Event Information": {
        "color": "#e74c3c",
        "fields": {
            "eventID":                     "Event ID",
            "event_date":                  "Event Date",
            "event_time":                  "Event Time",
            "event_timestamp":             "Event Timestamp (Unix)",
            "event_type":                  "Event Type",
            "event_type_certainty":        "Event Type Certainty",
            "event_creation_time":         "Event Creation Time",
            "event_author":                "Event Author",
            "event_agency":                "Event Agency",
            "event_evaluation_mode":       "Event Evaluation Mode",
            "event_evaluation_status":     "Event Evaluation Status",
            "preferred_origin_id":         "Preferred Origin ID",
            "preferred_magnitude_id":      "Preferred Magnitude ID",
        },
    },
    "Event Location": {
        "color": "#3498db",
        "fields": {
            "event_latitude":              "Event Latitude",
            "event_longitude":             "Event Longitude",
            "event_depth":                 "Event Depth (km)",
            "event_depth_uncertainty":     "Event Depth Uncertainty (km)",
            "event_latitude_uncertainty":  "Event Latitude Uncertainty (km)",
            "event_longitude_uncertainty": "Event Longitude Uncertainty (km)",
            "event_region":                "Event Region",
            "event_description":           "Event Description",
            "depth_constraint":            "Depth Constraint Type",
        },
    },
    "Event Magnitude": {
        "color": "#9b59b6",
        "fields": {
            "event_magnitude_type":             "Magnitude Type",
            "event_magnitude_value":            "Magnitude Value",
            "event_magnitude_uncertainty":      "Magnitude Uncertainty",
            "event_magnitude_station_count":    "Magnitude Station Count",
            "event_magnitude_azimuthal_gap":    "Magnitude Azimuthal Gap",
            "event_magnitude_method":           "Magnitude Method",
            "event_magnitude_author":           "Magnitude Author",
            "magnitude_evaluation_mode":        "Magnitude Evaluation Mode",
            "magnitude_evaluation_status":      "Magnitude Evaluation Status",
        },
    },
    "Origin Quality": {
        "color": "#f39c12",
        "fields": {
            "origin_quality_associated_phase_count":   "Associated Phase Count",
            "origin_quality_used_phase_count":         "Used Phase Count",
            "origin_quality_associated_station_count": "Associated Station Count",
            "origin_quality_used_station_count":       "Used Station Count",
            "origin_quality_depth_phase_count":        "Depth Phase Count",
            "origin_quality_standard_error":           "Standard Error (RMS, s)",
            "origin_quality_azimuthal_gap":            "Azimuthal Gap (°)",
            "origin_quality_secondary_azimuthal_gap":  "Secondary Azimuthal Gap (°)",
            "origin_quality_ground_truth_level":       "Ground Truth Level",
            "origin_quality_maximum_distance":         "Maximum Distance (°)",
            "origin_quality_minimum_distance":         "Minimum Distance (°)",
            "origin_quality_median_distance":          "Median Distance (°)",
            "location_quality_score":                  "Location Quality Score (0–100)",
        },
    },
    "Station Information": {
        "color": "#27ae60",
        "fields": {
            "station_network":           "Station Network",
            "station_code":              "Station Code",
            "station_location":          "Location Code",
            "station_channel":           "Channel Code",
            "station_latitude":          "Station Latitude",
            "station_longitude":         "Station Longitude",
            "station_elevation":         "Station Elevation (m)",
            "station_description":       "Station Description",
            "station_site_name":         "Site Name",
            "station_country":           "Country",
            "station_restricted_status": "Restricted Status",
            "station_start_date":        "Station Start Date",
            "station_end_date":          "Station End Date",
        },
    },
    "Pick Information": {
        "color": "#e67e22",
        "fields": {
            "pick_id":                "Pick ID",
            "pick_time":              "Pick Time",
            "pick_timestamp":         "Pick Timestamp (Unix)",
            "phase":                  "Phase",
            "pick_quality":           "Pick Quality",
            "pick_uncertainty":       "Pick Time Uncertainty (s)",
            "pick_polarity":          "Pick Polarity",
            "pick_onset":             "Pick Onset",
            "pick_evaluation_mode":   "Pick Evaluation Mode",
            "pick_evaluation_status": "Pick Evaluation Status",
            "pick_creation_time":     "Pick Creation Time",
            "pick_author":            "Pick Author",
            "pick_agency":            "Pick Agency",
            "pick_method":            "Pick Method",
            "pick_filter_id":         "Pick Filter ID",
        },
    },
    "Arrival Information & Usage": {
        "color": "#16a085",
        "fields": {
            "arrival_distance":                      "Distance (°)",
            "distance_km":                           "Distance (km)",
            "arrival_azimuth":                       "Azimuth (°)",
            "arrival_residual":                      "Time Residual (s)",
            "arrival_weight":                        "Weight",
            "arrival_time_used":                     "Time Used",
            "arrival_horizontal_slowness_residual":  "Horiz. Slowness Residual",
            "arrival_backazimuth_residual":          "Backazimuth Residual",
            "arrival_horizontal_slowness_weight":    "Horiz. Slowness Weight",
            "arrival_backazimuth_weight":            "Backazimuth Weight",
            "arrival_horizontal_slowness_used":      "Horiz. Slowness Used",
            "arrival_backazimuth_used":              "Backazimuth Used",
            "arrival_take_off_angle":                "Take-off Angle (°)",
            "arrival_take_off_angle_used":           "Take-off Angle Used",
        },
    },
    "Station Magnitude": {
        "color": "#8e44ad",
        "fields": {
            "station_magnitude_type":          "Sta. Magnitude Type",
            "station_magnitude_value":         "Sta. Magnitude Value",
            "station_magnitude_uncertainty":   "Sta. Magnitude Uncertainty",
            "station_magnitude_residual":      "Sta. Magnitude Residual",
            "station_magnitude_used":          "Sta. Magnitude Used in Network Mag",
            "station_magnitude_method":        "Sta. Magnitude Method",
            "station_magnitude_creation_time": "Sta. Magnitude Creation Time",
            "station_magnitude_author":        "Sta. Magnitude Author",
            "station_magnitude_agency":        "Sta. Magnitude Agency",
        },
    },
    "Calculated Times & Travel Times": {
        "color": "#34495e",
        "fields": {
            "sp_time":                  "S-P Time (s)",
            "sp_time_quality":          "S-P Quality (both P+S used)",
            "sp_time_used_only":        "S-P Time — used arrivals only (s)",
            "travel_time_p":            "P Travel Time (s)",
            "travel_time_s":            "S Travel Time (s)",
            "p_arrival_used":           "P Arrival Used",
            "s_arrival_used":           "S Arrival Used",
            "predicted_travel_time_p":  "Predicted P Travel Time (s)",
            "predicted_travel_time_s":  "Predicted S Travel Time (s)",
            "travel_time_residual_p":   "P Travel Time Residual (s)",
            "travel_time_residual_s":   "S Travel Time Residual (s)",
            "theoretical_arrival_time": "Theoretical Arrival Time",
            "observed_arrival_time":    "Observed Arrival Time",
            "vp_estimate":              "Apparent P Velocity (km/s)",
            "vs_estimate":              "Apparent S Velocity (km/s)",
            "vp_vs_ratio":              "Vp/Vs Ratio (ts/tp)",
        },
    },
    "Amplitude & Waveform": {
        "color": "#7f8c8d",
        "fields": {
            "amplitude_value":           "Amplitude Value",
            "amplitude_period":          "Amplitude Period (s)",
            "amplitude_snr":             "Signal-to-Noise Ratio",
            "amplitude_unit":            "Amplitude Unit",
            "amplitude_type":            "Amplitude Type",
            "amplitude_category":        "Amplitude Category",
            "amplitude_evaluation_mode": "Amplitude Evaluation Mode",
            "amplitude_creation_time":   "Amplitude Creation Time",
            "waveform_quality":          "Waveform Quality",
            "waveform_start_time":       "Waveform Start Time",
            "waveform_end_time":         "Waveform End Time",
        },
    },
    "Comments & Metadata": {
        "color": "#95a5a6",
        "fields": {
            "event_comments":       "Event Comments",
            "origin_comments":      "Origin Comments",
            "pick_comments":        "Pick Comments",
            "magnitude_comments":   "Magnitude Comments",
            "arrival_comments":     "Arrival Comments",
            "processing_info":      "Processing Info",
            "data_source":          "Data Source",
            "file_name":            "Source File Name",
            "processing_timestamp": "Processing Timestamp",
        },
    },
}

# Recommended fields — updated to include new derived fields
RECOMMENDED_FIELDS: list[str] = [
    "eventID", "event_date", "event_time",
    "event_latitude", "event_longitude", "event_depth",
    "event_magnitude_type", "event_magnitude_value",
    "origin_quality_azimuthal_gap", "origin_quality_used_phase_count",
    "origin_quality_standard_error", "location_quality_score",
    "depth_constraint",
    "station_network", "station_code",
    "pick_time", "phase",
    "arrival_distance", "distance_km", "arrival_azimuth",
    "arrival_time_used", "arrival_weight", "arrival_residual",
    "station_magnitude_value",
    "sp_time", "sp_time_quality",
    "travel_time_p", "travel_time_s",
    "vp_estimate", "vs_estimate", "vp_vs_ratio",
]

ALL_FIELDS: dict[str, str] = {
    k: v
    for cat in FIELD_CATEGORIES.values()
    for k, v in cat["fields"].items()
}
