"""
Extended export formats: HYPO71 phase file, Nordic (SEISAN), SQLite, Parquet.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


# ──────────────────────────────────────────────────────────────────────────────
# HYPO71 phase file
# ──────────────────────────────────────────────────────────────────────────────

def _hhmmss(time_str: Optional[str]) -> str:
    """'HH:MM:SS.mmm' → 'HHMM SS.ss'"""
    if not time_str:
        return "0000 00.00"
    try:
        pts = time_str.split(":")
        h, m = int(pts[0]), int(pts[1])
        s = float(pts[2]) if len(pts) > 2 else 0.0
        return f"{h:02d}{m:02d} {s:05.2f}"
    except Exception:
        return "0000 00.00"


def generate_hypo71(results: List[Dict]) -> str:
    """
    Generate a simplified HYPO71-compatible phase file.
    Returns a string ready to write to a .pha file.
    """
    lines: list[str] = [
        "  HYPO71 Phase File — Generated by SeisComP Extractor",
        "  Y2K extended format",
        "",
    ]

    events: dict[str, list[dict]] = {}
    for result in results:
        eid = result.get("eventId", "UNKNOWN")
        for rec in result.get("records", []):
            events.setdefault(eid, []).append(rec)

    for eid, records in events.items():
        if not records:
            continue
        ref = records[0]

        date = ref.get("event_date", "")
        time = ref.get("event_time", "")
        lat  = ref.get("event_latitude") or 0.0
        lon  = ref.get("event_longitude") or 0.0
        dep  = ref.get("event_depth") or 0.0
        mag  = ref.get("event_magnitude_value") or 0.0

        date_s = date.replace("-", "") if date else "00000000"
        time_s = _hhmmss(time)

        lat_deg = int(abs(lat))
        lat_min = (abs(lat) - lat_deg) * 60
        lon_deg = int(abs(lon))
        lon_min = (abs(lon) - lon_deg) * 60
        lat_ns = "N" if lat >= 0 else "S"
        lon_ew = "E" if lon >= 0 else "W"

        ev_line = (
            f"{date_s[:4]:4s}{date_s[4:6]:2s}{date_s[6:8]:2s} "
            f"{time_s} "
            f"{lat_ns}{lat_deg:2d}{lat_min:5.2f}"
            f"{lon_ew}{lon_deg:3d}{lon_min:5.2f}"
            f"{dep:6.2f}     {mag:4.1f}  EVENT {eid}"
        )
        lines.append(ev_line)

        for rec in records:
            sta   = (rec.get("station_code") or "     ")[:5]
            comp  = (rec.get("station_channel") or "   ")[:3]
            phase = (rec.get("phase") or "P")[:1].upper()
            wt    = rec.get("arrival_weight")
            wt_i  = 0 if wt is None else min(4, max(0, int((1.0 - float(wt)) * 4)))
            pt    = _hhmmss(rec.get("pick_time"))
            net   = (rec.get("station_network") or "  ")[:2]
            comp_z = comp[2] if len(comp) > 2 else "Z"

            lines.append(f"{sta:<5s}{comp_z:1s}{phase:1s}{wt_i:1d} {pt}  {net}")

        lines.append("")  # blank line between events

    return "\n".join(lines) + "\n"


# ──────────────────────────────────────────────────────────────────────────────
# Nordic (SEISAN) format
# ──────────────────────────────────────────────────────────────────────────────

def generate_nordic(results: List[Dict]) -> str:
    """
    Generate a Nordic/SEISAN format file.
    Type-1 header lines and Type-4 phase lines.
    """
    lines: list[str] = []

    events: dict[str, list[dict]] = {}
    for result in results:
        eid = result.get("eventId", "UNKNOWN")
        for rec in result.get("records", []):
            events.setdefault(eid, []).append(rec)

    for eid, records in events.items():
        if not records:
            continue
        ref = records[0]

        date  = ref.get("event_date", "")
        time  = ref.get("event_time", "")
        lat   = ref.get("event_latitude")
        lon   = ref.get("event_longitude")
        dep   = ref.get("event_depth")
        mag   = ref.get("event_magnitude_value")
        mag_t = ref.get("event_magnitude_type", "L")
        rms   = ref.get("origin_quality_standard_error")
        nstat = ref.get("origin_quality_used_station_count") or 0
        agency = (ref.get("event_agency") or "   ")[:3]

        yr = date[:4] if date else "    "
        mo = date[5:7] if len(date) >= 7 else "  "
        dy = date[8:10] if len(date) >= 10 else "  "
        hh = time[:2] if time else "  "
        mn = time[3:5] if len(time) >= 5 else "  "
        ss = time[6:11] if len(time) >= 11 else "     "

        lat_f = abs(lat) if lat is not None else 0.0
        lon_f = abs(lon) if lon is not None else 0.0
        lat_i = " " if (lat or 0) >= 0 else "S"
        lon_i = " " if (lon or 0) >= 0 else "W"
        dep_f = dep if dep is not None else 0.0
        mag_f = mag if mag is not None else 0.0
        rms_f = rms if rms is not None else 0.0
        mag_code = str(mag_t or "L")[0].upper()

        line1 = (
            f" {yr} {mo}{dy} {hh}{mn} {ss:<5s} "
            f"{lat_i}{lat_f:6.3f} {lon_i}{lon_f:7.3f} {dep_f:6.1f} "
            f" F {agency:<3s}{nstat:3d}{rms_f:4.2f} "
            f"{mag_code}{mag_f:4.1f}             "
        )
        lines.append(f"{line1:<79s}1")

        for rec in records:
            sta   = (rec.get("station_code") or "     ")[:5]
            comp  = (rec.get("station_channel") or "   ")[:3]
            phase = (rec.get("phase") or "P")[:6]
            wt    = rec.get("arrival_weight")
            wt_f  = float(wt) if wt is not None else 1.0
            ptime = rec.get("pick_time") or "00:00:00.000"
            pts   = ptime.split(":")
            ph    = pts[0] if len(pts) > 0 else "00"
            pm    = pts[1] if len(pts) > 1 else "00"
            ps    = pts[2] if len(pts) > 2 else "00.000"
            tres  = rec.get("arrival_residual") or 0.0
            dist  = rec.get("arrival_distance") or 0.0
            az    = rec.get("arrival_azimuth") or 0.0

            line4 = (
                f" {sta:<5s} {comp:<3s}  {phase:<6s}{wt_f:3.1f} "
                f"{ph}{pm}{ps:<7s} "
                f"{tres:+6.3f} {dist:6.2f} {az:5.1f}"
            )
            lines.append(f"{line4:<79s}4")

        lines.append(" ")  # blank separator

    return "\n".join(lines) + "\n"


# ──────────────────────────────────────────────────────────────────────────────
# SQLite export
# ──────────────────────────────────────────────────────────────────────────────

_EVENT_LEVEL_FIELDS = frozenset({
    "eventID", "event_date", "event_time", "event_timestamp", "event_type",
    "event_type_certainty", "event_creation_time", "event_author", "event_agency",
    "event_evaluation_mode", "event_evaluation_status",
    "preferred_origin_id", "preferred_magnitude_id",
    "event_latitude", "event_longitude", "event_depth",
    "event_depth_uncertainty", "event_latitude_uncertainty",
    "event_longitude_uncertainty", "event_region", "event_description",
    "depth_constraint",
    "event_magnitude_type", "event_magnitude_value", "event_magnitude_uncertainty",
    "event_magnitude_station_count", "event_magnitude_azimuthal_gap",
    "event_magnitude_method", "event_magnitude_author",
    "magnitude_evaluation_mode", "magnitude_evaluation_status",
    "origin_quality_associated_phase_count", "origin_quality_used_phase_count",
    "origin_quality_associated_station_count", "origin_quality_used_station_count",
    "origin_quality_depth_phase_count", "origin_quality_standard_error",
    "origin_quality_azimuthal_gap", "origin_quality_secondary_azimuthal_gap",
    "origin_quality_ground_truth_level", "origin_quality_maximum_distance",
    "origin_quality_minimum_distance", "origin_quality_median_distance",
    "location_quality_score",
    "event_comments", "origin_comments", "magnitude_comments",
    "file_name", "processing_timestamp",
})


def export_to_sqlite(
    results: List[Dict],
    output_path: str | Path,
    selected_fields: List[str],
) -> Path:
    """
    Write records to a SQLite database with two tables:
      events   — one row per event (event-level fields)
      arrivals — one row per arrival (all other selected fields + event_id FK)
    """
    import sqlite3

    output_path = Path(output_path)

    ev_fields  = [f for f in selected_fields if f in _EVENT_LEVEL_FIELDS]
    arr_fields = [f for f in selected_fields if f not in _EVENT_LEVEL_FIELDS]

    def _col_type(f: str) -> str:
        # Numeric fields get REAL, everything else TEXT
        _numeric = {
            "event_timestamp", "event_latitude", "event_longitude", "event_depth",
            "event_depth_uncertainty", "event_latitude_uncertainty",
            "event_longitude_uncertainty", "event_magnitude_value",
            "event_magnitude_uncertainty", "event_magnitude_station_count",
            "event_magnitude_azimuthal_gap", "location_quality_score",
            "origin_quality_standard_error", "origin_quality_azimuthal_gap",
            "origin_quality_used_phase_count", "origin_quality_used_station_count",
            "origin_quality_minimum_distance", "origin_quality_maximum_distance",
            "arrival_distance", "distance_km", "arrival_azimuth",
            "arrival_residual", "arrival_weight",
            "travel_time_p", "travel_time_s",
            "sp_time", "sp_time_used_only",
            "vp_estimate", "vs_estimate", "vp_vs_ratio",
            "station_latitude", "station_longitude", "station_elevation",
            "station_magnitude_value", "station_magnitude_uncertainty",
            "station_magnitude_residual",
        }
        return "REAL" if f in _numeric else "TEXT"

    with sqlite3.connect(output_path) as conn:
        cur = conn.cursor()
        cur.execute("DROP TABLE IF EXISTS arrivals")
        cur.execute("DROP TABLE IF EXISTS events")

        ev_col_defs = ", ".join(f'"{f}" {_col_type(f)}' for f in ev_fields)
        cur.execute(f"""CREATE TABLE events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT NOT NULL UNIQUE
            {(',' + ev_col_defs) if ev_col_defs else ''}
        )""")

        arr_col_defs = ", ".join(f'"{f}" {_col_type(f)}' for f in arr_fields)
        cur.execute(f"""CREATE TABLE arrivals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT NOT NULL REFERENCES events(event_id)
            {(',' + arr_col_defs) if arr_col_defs else ''}
        )""")

        seen: set[str] = set()
        for result in results:
            eid = result.get("eventId", "unknown")
            records = result.get("records", [])
            if not records:
                continue
            ref = records[0]

            if eid not in seen:
                if ev_fields:
                    vals = [ref.get(f) for f in ev_fields]
                    ph   = ",".join("?" * len(ev_fields))
                    cols = ",".join(f'"{f}"' for f in ev_fields)
                    cur.execute(
                        f'INSERT INTO events (event_id,{cols}) VALUES (?,{ph})',
                        [eid] + vals,
                    )
                else:
                    cur.execute('INSERT INTO events (event_id) VALUES (?)', [eid])
                seen.add(eid)

            for rec in records:
                if arr_fields:
                    vals = [rec.get(f) for f in arr_fields]
                    ph   = ",".join("?" * len(arr_fields))
                    cols = ",".join(f'"{f}"' for f in arr_fields)
                    cur.execute(
                        f'INSERT INTO arrivals (event_id,{cols}) VALUES (?,{ph})',
                        [eid] + vals,
                    )
                else:
                    cur.execute('INSERT INTO arrivals (event_id) VALUES (?)', [eid])

        conn.commit()

    return output_path


# ──────────────────────────────────────────────────────────────────────────────
# Parquet export
# ──────────────────────────────────────────────────────────────────────────────

def export_to_parquet(
    results: List[Dict],
    output_path: str | Path,
    selected_fields: List[str],
) -> Path:
    """
    Write all records to a single Parquet file.
    Requires: pyarrow  (pip install pyarrow)
    """
    try:
        import pyarrow as pa
        import pyarrow.parquet as pq
    except ImportError as exc:
        raise ImportError(
            "Parquet export requires pyarrow. Install with: pip install pyarrow"
        ) from exc

    output_path = Path(output_path)
    rows: list[dict] = []

    for result in results:
        eid = result.get("eventId", "unknown")
        for rec in result.get("records", []):
            row = {"_event_id": eid}
            for f in selected_fields:
                row[f] = rec.get(f)
            rows.append(row)

    all_cols = ["_event_id"] + selected_fields

    if not rows:
        table = pa.table({c: pa.array([], type=pa.string()) for c in all_cols})
    else:
        col_data: dict[str, list] = {c: [] for c in all_cols}
        for row in rows:
            for c in all_cols:
                col_data[c].append(row.get(c))
        table = pa.table(col_data)

    pq.write_table(table, output_path, compression="snappy")
    return output_path
